- name: Check if Podman is installed
  command: rpm -q podman
  register: podman_installed
  ignore_errors: yes

- name: Remove Podman packages
  dnf:
    name:
      - podman
      - podman-gvproxy
      - cockpit-podman
      - podman-plugins
      - podman-catatonit
      - container-selinux
      - containernetworking-plugins
      - containers-common
    state: absent
  when: podman_installed.rc == 0  

- name: Remove Podman containers directory
  file:
    path: /var/lib/containers
    state: absent
    force: yes
  when: podman_installed.rc == 0 
