
---
- name: Detect OS and version
  ansible.builtin.setup:

- name: Disable SELinux temporarily (RedHat/CentOS)
  command: setenforce 0
  when: ansible_facts['os_family'] == 'RedHat'

- name: Disable SELinux permanently (RedHat/CentOS)
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing$'
    line: 'SELINUX=permissive'
  when: ansible_facts['os_family'] == 'RedHat'

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Stop and disable firewalld (RedHat/CentOS)
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_facts['os_family'] == 'RedHat'

- name: Stop and disable ufw (Ubuntu/Debian)
  service:
    name: ufw
    state: stopped
    enabled: no
  when: ansible_facts['os_family'] == 'Debian'

- name: Load necessary kernel modules for containerd
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf

- name: Load kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter
  args:
    warn: false
    
- name: Configure sysctl for Kubernetes networking
  copy:
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: Apply sysctl settings
  command: sysctl --system

- name: Disable swap
  command: swapoff -a

- name: Remove swap entries from /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '# \1'

- name: Reload fstab to apply changes
  command: mount -a

- name: Add master and worker nodes to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    state: present
    create: yes
  loop: "{{ groups['all'] }}"
  when:
    - hostvars[item].ansible_host is defined
    - "'{{ hostvars[item].ansible_host }} {{ item }}' not in lookup('file', '/etc/hosts')"
