---
- name: Check if Kubernetes master is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: master_initialized

- name: Initialize Kubernetes master node
  command: kubeadm init --skip-phases=addon/kube-proxy --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all --upload-certs --control-plane-endpoint "{{ vip }}:{{ port }}"
  register: master_init_output
  when: not master_initialized.stat.exists

- name: Create .kube directory if it does not exist
  file:
    path: "/root/.kube"
    state: directory 
    mode: '0755'
  when: not master_initialized.stat.exists

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    remote_src: yes
  when: not master_initialized.stat.exists

- name: Set ownership of kube config file
  command: chown {{ ansible_user }}:{{ ansible_user }} /root/.kube/config
  when: not master_initialized.stat.exists

- name: Sao chép tệp từ máy chủ về máy Ansible
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: '0644'
    flat: yes