---
- name: uninstall cilium
  commamd: helm uninstall cilium --namespace kube-system

- name: Reset kubeadm on the worker node (clean up previous attempts)
  command: kubeadm reset -f
  ignore_errors: yes

- name: Remove residual Kubernetes files (optional cleanup)
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - /var/lib/etcd
    - /var/lib/kubelet/*
  ignore_errors: yes

- name: Stop and disable kubelet service (if running)
  systemd:
    name: kubelet
    state: stopped
    enabled: yes
  ignore_errors: yes
