- name: Add Helm repository
  shell: |
    helm repo add cilium https://helm.cilium.io/
    helm repo add signoz https://charts.signoz.io/
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
    helm repo add jetstack https://charts.jetstack.io
    helm repo update

- name: Check if Cilium is already installed
  shell: kubectl get pods -n kube-system | grep cilium
  register: cilium_check
- name: Install Cilium CNI
  shell: |
    SEED=$(head -c12 /dev/urandom | base64 -w0) && \
    helm upgrade -i cilium cilium/cilium --version 1.16.3 \
      --namespace kube-system \
      --set kubeProxyReplacement=true \
      --set k8sServiceHost={{ vip }} \
      --set k8sServicePort={{ port }} \
      --reuse-values \
      --set hubble.relay.enabled=true \
      --set hubble.ui.enabled=true \
      --set loadBalancer.algorithm=maglev \
      --set maglev.tableSize=131071 \
      --set maglev.hashSeed=$SEED
  when: cilium_check.rc != 0
- name: Check if ingress-nginx is already installed
  shell: kubectl get pods -n ingress-nginx | grep ingress-nginx-controller
  register: ingress_check
- name: Install Ingress-nginx
  shell: |
    helm upgrade -i ingress-nginx ingress-nginx \
      --repo https://kubernetes.github.io/ingress-nginx \
      --namespace ingress-nginx --create-namespace \
      --set controller.metrics.enabled=true \
      --set-string controller.podAnnotations."prometheus\.io/scrape"="true" \
      --set controller.service.nodePorts.http=30080 \
      --set controller.service.nodePorts.https=30443 \
      --set-string controller.podAnnotations."prometheus\.io/port"="10254" --create-namespace
  when: ingress_check.rc != 0
  
- name: Check if Metric Server is already installed
  shell: kubectl get pods -n cattle-system | grep metric-server
  register: metrics_check
- name: Install Metric Server
  command: kubectl apply -f /opt/metric-server.yaml
  when: metrics_check.rc != 0

- name: Check if Rancher is already installed
  shell: kubectl get pods -n cattle-system | grep rancher
  register: rancher_check
- name: Install Rancher
  shell: |
    kubectl create namespace cattle-system
    kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.1/cert-manager.crds.yaml
    helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.16.1
    helm upgrade -i rancher rancher-stable/rancher --namespace cattle-system --set letsEncrypt.email="iducok@idevops.io.vn" --set hostname=rancher.idevops.io.vn --set ingress.ingressClassName=nginx --set global.cattle.psp.enabled=false --set ingress.tls.source=rancher --set ingress.tls.source=letsEncrypt --set ingress.tls.source=secret --set bootstrapPassword=admin
  when: rancher_check.rc != 0