#!/usr/bin/env bash
set -euo pipefail

# Tạo file config.txt từ danh sách repository trong ECR
# Mỗi dòng: <deployment>:<image_uri>:sha256:<digest>
# deployment mặc định = tên repository
#
# Biến môi trường:
#   REGISTRY_ID (mặc định 058264243496)
#   REGION (mặc định ap-southeast-1)
#   OUTPUT_PATH (mặc định idevops/check-image-ecr/app/config.txt)

REGISTRY_ID="${REGISTRY_ID:-058264243496}"
REGION="${REGION:-ap-southeast-1}"
OUTPUT_PATH="${OUTPUT_PATH:-idevops/check-image-ecr/app/config.txt}"

command -v aws >/dev/null 2>&1 || { echo "ERROR: aws CLI chưa cài đặt" >&2; exit 1; }

echo "# Auto-generated by gen-config-from-ecr.sh at $(date)" > "$OUTPUT_PATH"
echo "# Format: <deployment>:<image_uri>:sha256:<digest>" >> "$OUTPUT_PATH"
echo "# Region=$REGION Registry=$REGISTRY_ID" >> "$OUTPUT_PATH"

# Lấy toàn bộ repository trong registry
repos=$(aws ecr describe-repositories \
  --registry-id "$REGISTRY_ID" \
  --region "$REGION" \
  --query 'repositories[].repositoryName' \
  --output text)

if [[ -z "$repos" ]]; then
  echo "WARNING: Không lấy được danh sách repository. Kiểm tra quyền AWS hoặc tham số." >&2
  exit 0
fi

for repo in $repos; do
  image_uri="${REGISTRY_ID}.dkr.ecr.${REGION}.amazonaws.com/${repo}:latest"
  digest=$(aws ecr list-images \
    --repository-name "$repo" \
    --registry-id "$REGISTRY_ID" \
    --region "$REGION" \
    --query 'imageIds[?imageTag==`latest`].imageDigest' \
    --output text 2>/dev/null || true)

  if [[ -z "$digest" || "$digest" == "None" ]]; then
    digest_note="sha256:NONE"
  else
    digest_note="$digest"
  fi

  echo "${repo}:${image_uri}:${digest_note}" >> "$OUTPUT_PATH"
done

echo "Đã sinh file cấu hình: $OUTPUT_PATH"