{{- if .Values.alertmanagerConfigs.enabled }}
{{- $selectorLabel := default "alertmanager" .Values.alertmanagerConfigs.selectorLabel }}
{{- $alertmanagerName := default "main" .Values.alertmanagerConfigs.alertmanagerName }}
{{- $webhookURL := .Values.alertmanagerConfigs.webhookURL }}
{{- $common := .Values.alertmanagerConfigs.common }}
{{- $globalToken := default "" .Values.alertmanagerConfigs.bearer.token }}
{{- $hasBeta := .Capabilities.APIVersions.Has "monitoring.coreos.com/v1beta1" }}
{{- $hasAlpha := .Capabilities.APIVersions.Has "monitoring.coreos.com/v1alpha1" }}
{{- if or $hasBeta $hasAlpha }}
{{- $apiVersion := ternary "monitoring.coreos.com/v1beta1" "monitoring.coreos.com/v1alpha1" $hasBeta }}
{{- range $i, $item := .Values.alertmanagerConfigs.items }}
apiVersion: {{ $apiVersion }}
kind: AlertmanagerConfig
metadata:
  name: {{ printf "%s-%s" (include "webhook-alert-gapo.fullname" $) $item.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $item.namespace }}
  labels:
    {{ $selectorLabel }}: {{ $alertmanagerName }}
spec:
  route:
    matchers:
      - name: namespace
        value: ^({{ $item.namespace }})$
        matchType: =~
      {{- if $common.systemRegex }}
      - name: system
        value: {{ $common.systemRegex | quote }}
        matchType: =~
      {{- end }}
    groupBy:
      {{- range $common.groupBy }}
      - {{ . }}
      {{- end }}
    groupWait: {{ default "30s" $common.groupWait }}
    groupInterval: {{ default "5m" $common.groupInterval }}
    repeatInterval: {{ default "4h" $common.repeatInterval }}
    receiver: {{ printf "blackhole-%s" $item.name }}
    routes:
      {{- with $item.whitelist }}
      {{- if .instances.ipRegex }}
      - receiver: {{ printf "webhook-alert-gapo-%s" $item.name }}
        matchers:
          - name: instance
            value: {{ .instances.ipRegex | quote }}
            matchType: =~
          {{- if .severities }}
          - name: severity
            value: ^({{ join "|" .severities }})$
            matchType: =~
          {{- end }}
          {{- if .jobs }}
          - name: job
            value: ^({{ join "|" .jobs }})$
            matchType: =~
          {{- end }}
          {{- if .alertnames }}
          - name: alertname
            value: ^({{ join "|" .alertnames }})$
            matchType: =~
          {{- end }}
      {{- end }}
      {{- if .instances.hostRegex }}
      - receiver: {{ printf "webhook-alert-gapo-%s" $item.name }}
        matchers:
          - name: instance
            value: {{ .instances.hostRegex | quote }}
            matchType: =~
          {{- if .severities }}
          - name: severity
            value: ^({{ join "|" .severities }})$
            matchType: =~
          {{- end }}
          {{- if .jobs }}
          - name: job
            value: ^({{ join "|" .jobs }})$
            matchType: =~
          {{- end }}
          {{- if .alertnames }}
          - name: alertname
            value: ^({{ join "|" .alertnames }})$
            matchType: =~
          {{- end }}
      {{- end }}
      {{- end }}
      {{- with $item.blacklist }}
      {{- if .alertnames }}
      - receiver: {{ printf "blackhole-%s" $item.name }}
        matchers:
          - name: alertname
            value: ^({{ join "|" .alertnames }})$
            matchType: =~
      {{- end }}
      {{- if .jobs }}
      - receiver: {{ printf "blackhole-%s" $item.name }}
        matchers:
          - name: job
            value: ^({{ join "|" .jobs }})$
            matchType: =~
      {{- end }}
      {{- end }}
  receivers:
    - name: {{ printf "webhook-alert-gapo-%s" $item.name }}
      webhookConfigs:
        - url: {{ $webhookURL | quote }}
          sendResolved: true
          httpConfig:
            followRedirects: true
            {{- $itemToken := default $globalToken $item.bearerToken }}
            {{- if ne (default "" $itemToken) "" }}
            bearerTokenSecret:
              name: {{ printf "%s-am-bearer-%s" (include "webhook-alert-gapo.fullname" $) $item.name | trunc 63 | trimSuffix "-" }}
              key: token
            {{- end }}
    - name: {{ printf "blackhole-%s" $item.name }}
---
{{- end }}
{{- end }}
{{- end }}