{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webhook-alert-gapo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "webhook-alert-gapo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
automountServiceAccountToken: false
{{- end }}