{{- $hasVault := .Capabilities.APIVersions.Has "secrets.hashicorp.com/v1beta1" }}
{{- if and $hasVault .Values.vaultStaticSecret (default false .Values.vaultStaticSecret.enabled) }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ default "webhook-alert-gapo-vault-static" .Values.vaultStaticSecret.name }}
spec:
  type: kv-v2
  mount: {{ .Values.vaultStaticSecret.kv2Mount }}
  path: {{ .Values.vaultStaticSecret.kv2Path }}
  destination:
    name: {{ .Values.vaultStaticSecret.destinationSecretName }}
    create: true
  refreshAfter: {{ default "30s" .Values.vaultStaticSecret.refreshAfter }}
  vaultAuthRef: {{ default "static-auth" .Values.vaultStaticSecret.vaultAuthRef }}
{{- end }}
