apiVersion: v1
kind: Service
metadata:
  name: iam-esb-db
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: iam-esb-db
  ports:
  - name: mysql-jdbc
    protocol: TCP
    port: 3306
    targetPort: 3306
