---
- name: Setup SSH Key Authentication
  hosts: localhost
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  become: false
  vars_files:
    - vars/main.yml
  tasks:
    - include_tasks: tasks/0_config_server_ansible.yml

- name: Kubernetes Cluster Setup
  hosts: all
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  become: yes
  gather_facts: yes
  vars_files:
    - vars/main.yml
  tasks:
    - include_tasks: tasks/main.yml
  handlers:
    - name: Restart Keepalived
      systemd:
        name: keepalived
        state: restarted
        
    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted