---
- name: Kubernetes Cluster Setup
  hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  tasks:
    - include_tasks: tasks/5_reset_cluster.yml
    - name: Stop keepalived
      ansible.builtin.systemd:
        name: keepalived
        state: stopped

    - name: List all network interfaces
      shell: "ls /sys/class/net | grep -v 'lo'"
      register: net_interfaces

    - name: Remove all interfaces except the first two
      shell: "ip link delete {{ item }}"
      loop: "{{ net_interfaces.stdout_lines[1:] }}"
      ignore_errors: yes 