---
- name: Tạo thư mục đích trên máy Ansible
  delegate_to: localhost
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Add kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && rm -rf kubectl

- name: Install Python3 and pip3 on Ansible control node (RHEL/CentOS)
  yum:
    name:
      - python3
      - python3-pip
      - python2-pip
    state: present
  when: ansible_os_family == "RedHat"
  delegate_to: localhost
  become: yes

- name: Install pexpect library on Ansible control node
  pip:
    name: pexpect
    executable: pip
  delegate_to: localhost
  become: yes

- name: Remove existing SSH key for remote host from known_hosts
  delegate_to: localhost
  shell: ssh-keygen -R {{ ansible_host }}
  ignore_errors: yes  # Ignore errors in case the entry does not exist

- name: Copy SSH public key to remote servers
  delegate_to: localhost
  expect:
    command: ssh-copy-id -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_host }}
    responses:
      (?i)password: "{{ ansible_ssh_pass }}"
