---
- name: Get default network interface
  ansible.builtin.shell: "ip route | grep default | awk '{print $5}'"
  register: default_interface

- name: Configure Keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  vars:
    interface: "{{ default_interface.stdout }}"
  notify:
    - Restart Keepalived

- name: Enable and start Keepalived service
  systemd:
    name: keepalived
    enabled: yes
    state: restarted

