---
- name: Backup existing etcd.yaml on the remote host
  command:
    cmd: cp /etc/kubernetes/manifests/etcd.yaml /etc/kubernetes/manifests/etcd.yaml.bak
  args:
    creates: /etc/kubernetes/manifests/etcd.yaml.bak

- name: Add --metrics=extensive to etcd.yaml
  lineinfile:
    path: /etc/kubernetes/manifests/etcd.yaml
    insertafter: 'command:'
    line: "    - --metrics=extensive"