{
 "title": "Node Exporter Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Server Resource Overview",
   "type": "table",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_uname_info{} - 0", "legendFormat": "主机名" },
    {
     "expr": "sum(time() - node_boot_time_seconds{})by(instance) or sum(time() - windows_system_system_up_time{}) by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{} - 0 or windows_cs_physical_memory_bytes{} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"}) by (instance) or sum(windows_cs_logical_processors{} - 0) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance)) * 100 or 100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{} / (node_memory_MemTotal_bytes{})))* 100 or 100 - 100 * windows_os_physical_memory_free_bytes{} / windows_cs_physical_memory_bytes{}",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "avg(rate(node_disk_read_bytes_total{}[$interval])) by (instance) or avg(rate(windows_logical_disk_read_bytes_total{}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "avg(rate(node_disk_written_bytes_total{}[$interval])) by (instance) or avg(rate(windows_logical_disk_write_bytes_total{}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "avg(rate(node_network_receive_bytes_total{}[$interval])*8) by (instance) or avg(rate(windows_net_bytes_received_total{}[$interval])) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "avg(rate(node_network_transmit_bytes_total{}[$interval])*8) by (instance) or avg(rate(windows_net_bytes_sent_total{}[$interval])) by (instance) ",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ((1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance)) * 100 ) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[$interval])) * 100)) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_g}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_g}:9100\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_h}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_h}:9100\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_i}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_i}:9100\"})",
     "legendFormat": "${server_i}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_j}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_j}:9100\"})",
     "legendFormat": "${server_j}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_k}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_k}:9100\"})",
     "legendFormat": "${server_k}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_l}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_l}:9100\"})",
     "legendFormat": "${server_l}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_m}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_m}:9100\"})",
     "legendFormat": "${server_m}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_n}:9110\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_n}:9110\"})",
     "legendFormat": "${server_n}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_o}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_o}:9100\"})",
     "legendFormat": "${server_o}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_p}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_p}:9100\"})",
     "legendFormat": "${server_p}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 - ((node_memory_MemAvailable_bytes{} * 100) / node_memory_MemTotal_bytes{})) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(100 - 100 * windows_os_physical_memory_free_bytes{} / windows_cs_physical_memory_bytes{}) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_g}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_g}:9100\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_h}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_h}:9100\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_i}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_i}:9100\"})",
     "legendFormat": "${server_i}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_j}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_j}:9100\"})",
     "legendFormat": "${server_j}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_k}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_k}:9100\"})",
     "legendFormat": "${server_k}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_l}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_l}:9100\"})",
     "legendFormat": "${server_l}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_m}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_m}:9100\"})",
     "legendFormat": "${server_m}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_n}:9110\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_n}:9110\"})",
     "legendFormat": "${server_n}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_o}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_o}:9100\"})",
     "legendFormat": "${server_o}"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"${server_p}:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"${server_p}:9100\"})",
     "legendFormat": "${server_p}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "table",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*container.*|/boot.*\"}-0) by (instance,mountpoint,device,fstype) or sum(label_replace(windows_logical_disk_size_bytes{volume !~\".*Harddisk.*\"},\"mountpoint\",\"$1\",\"volume\",\"(.*)\")) by (instance,mountpoint)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes {fstype=~\"ext.*|xfs\",mountpoint !~\".*container.*|/boot.*\"}-0) by (instance,mountpoint,device,fstype) or sum(label_replace(windows_logical_disk_free_bytes{volume !~\".*Harddisk.*\"},\"mountpoint\",\"$1\",\"volume\",\"(.*)\")) by (instance,mountpoint)"
    },
    {
     "expr": "sum(((node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*container.*|/boot.*\"}  - node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*container.*\"})) / node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*container.*\"}  * 100) by (instance,device,mountpoint) or sum(label_replace(100 - ((windows_logical_disk_free_bytes{volume !~\".*Harddisk.*\"})/ (windows_logical_disk_size_bytes{volume !~\".*Harddisk.*\"} > 10993377382 ))*100,\"mountpoint\",\"$1\",\"volume\",\"(.*)\"))  by (instance,mountpoint)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance)) * 100 or 100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{} / (node_memory_MemTotal_bytes{})))* 100 or 100 - 100 * windows_os_physical_memory_free_bytes{} / windows_cs_physical_memory_bytes{}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_read_bytes_total{}[$interval])) by (instance) or avg(rate(windows_logical_disk_read_bytes_total{}[$interval])) by (instance)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_written_bytes_total{}[$interval])) by (instance) or avg(rate(windows_logical_disk_write_bytes_total{}[$interval])) by (instance)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(node_network_receive_bytes_total{}[$interval])*8) by (instance) or avg(rate(windows_net_bytes_received_total{}[$interval])) by (instance)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(node_network_transmit_bytes_total{}[$interval])*8) by (instance) or avg(rate(windows_net_bytes_sent_total{}[$interval])) by (instance) ",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}